name: Deploy to firebase

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./functions
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
      - name: Install
        run: npm ci
      - name: Install firebase tools
        run: npm install firebase-tools -g
      - name: Exports credentials
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY_BASE64" | base64 -d > /tmp/gcp_key.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp_key.json
        env:
          GCP_SERVICE_ACCOUNT_KEY_BASE64: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_BASE64 }}
      - name: Deploy to firebase
        run: |
          firebase use --add "$PROJECT_ID"
          firebase deploy --only functions
        env:
         FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}